name: dnet_buy 
description: "Plateforme de gestion de tickets WiFi pour portails captifs."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# --- DÉPENDANCES DE L'APPLICATION ---
dependencies:
  flutter:
    sdk: flutter

  # Core
  get: ^4.6.6               # Gestion d'état, injection de dépendances et routing
  get_storage: ^2.1.1       # Stockage local clé-valeur simple et rapide
  
  # UI & Utilitaires
  cupertino_icons: ^1.0.8     # Icônes de style iOS
  intl: ^0.19.0             # Pour le formatage des dates et des nombres
  file_picker: ^10.2.1         # Pour la sélection de fichiers (upload CSV)
  flutter_lints: ^3.0.2       
  cloud_functions: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  firebase_auth: ^6.0.0
  crypto: ^3.0.6
  logger: ^2.6.1
  csv: ^6.0.0

# --- DÉPENDANCES DE DÉVELOPPEMENT ---
dev_dependencies:
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter

# --- CONFIGURATION FLUTTER ---
flutter:
  uses-material-design: true

  # --- GESTION DES ASSETS ---
  assets:
    - assets/images/
    - assets/images/splash.gif

  # --- GESTION DES POLICES (FONTS) ---
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700


# --- CONFIGURATION DU SPLASH SCREEN NATIF ---
flutter_native_splash:
  # Couleur de fond du splash screen
  color: "#ffffff" 
  image_web: assets/images/splash.gif
  image: assets/images/splash.gif
  web: true
  web_image_mode: center